AWSTemplateFormatVersion: 2010-09-09
Description: template to launch ec2, install and run NginX.

# to avoid hardcoding variables
Parameters:
  EnvironmentType:
    Description: "Specify the Environment type of the stack."
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
  AmiID:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id> 
    # public parameters can be gotten by running the command:
    # aws ssm get-parameters-by-path \
    #   --path /aws/service/ami-amazon-linux-latest \
    #   --query 'Parameters[].Name'
    Description: "Ami image ID."
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
  KeyPairName:
    Type: String
    Description: The name of an existing Amazon EC2 key pair.

Mappings:
  EnvironmentToInstanceType:
    dev:
      InstanceType: t3.micro
    test:
      InstanceType: t2.micro
    prod:
      InstanceType: t2.small

# provisioning your stack
Resources:
  # the ec2 instance
  NginxInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !FindInMap [
          EnvironmentToInstanceType,
          !Ref EnvironmentType,
          InstanceType,
        ]
      ImageId: !Ref AmiID  # Amazon Linux AMI 
      KeyName: !Ref KeyPairName
      UserData: 
        Fn::Base64: 
          !Sub |
              #!/bin/bash
              sudo yum update -y
              sudo amazon-linux-extras install nginx1 -y 
              sudo systemctl enable nginx
              sudo systemctl start nginx
      SecurityGroups: [
       !Ref NginxSecurityGroup
      ]
      Monitoring: True

  # a security group to allow ipv4 access
  NginxSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Join ["-", [nginx-instance-security-group, !Ref EnvironmentType]]
      GroupDescription: "Allow HTTP/HTTPS and SSH inbound and outbound traffic"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
